task/products/urls.py
from django.urls import path
from .views import ProductView, ProductDetailView, user_in_group

app_name = 'products'

urlpatterns = [
    path('', ProductView.as_view(), name='index_page'),
    path('<int:pk>/detail/', ProductDetailView.as_view(), name='detail_page'),
    path('<int:pk>/buy/', user_in_group, name='buy_page')
]

task/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UserCreateView, LoginUser, LogoutUser

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.products.urls', namespace='products')),
    path('create/', UserCreateView.as_view(), name='register_page'),
    path('login/', LoginUser.as_view(), name='login_page'),
    path('logout/', LogoutUser.as_view(), name='logout'),

]

task/groups/models.py
from django.db import models
from task.users.models import CustomUser
from task.products.models import Product


class Group(models.Model):
    name = models.CharField(max_length=255)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='groups')
    users = models.ManyToManyField(CustomUser, blank=True)

    def __str__(self):
        return self.name

task/lessons/models.py
from django.db import models
from task.products.models import Product


class Lesson(models.Model):
    name = models.CharField(max_length=255, unique=True)
    video = models.URLField(max_length=200, unique=True)
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT,
        related_name='lessons',
    )

    def __str__(self):
        return self.name

task/products/models.py
from django.db import models
from task.users.models import CustomUser


# Create your models here.
class Product(models.Model):
    name = models.CharField(unique=True, max_length=255)
    start_date = models.DateTimeField(auto_now_add=False)
    price = models.IntegerField()
    min_users = models.IntegerField()
    max_users = models.IntegerField()
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='author'
    )

    def __str__(self):
        return self.name

    def is_bought(self, user):
        return True if user in self.groups else False

task/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):

    def __str__(self):
        return self.username

task/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from task.users.models import CustomUser


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control'}
                               ))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control'}
                                ))
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control'}
                                ))

    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Имя пользователя'}
                               ))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Пароль'}
                               ))

task/groups/views.py
from django.shortcuts import render

# Create your views here.

task/products/views.py
from django.contrib import messages
from django.shortcuts import redirect
from django.utils import timezone
from .models import Product
from django.views.generic import ListView, DetailView
from task.mixins import LoginRequiredMixin


class ProductView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'index.html'


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'detail.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        product = Product.objects.get(pk=self.kwargs['pk'])
        groups = product.groups.all()
        all_users = []
        for group in groups:
            all_users.extend(group.users.all())
        max_count = product.groups.all().count() * product.max_users
        if len(all_users) >= max_count:
            perm = False
        else:
            perm = True
        if product.start_date > timezone.now():
            time_perm = True
        else:
            time_perm = False
        data['lessons_of_product'] = product.lessons.all()
        data['time_perm'] = time_perm
        data['permission'] = perm
        return data


def same_distribution(request, all_users, groups, product):

    """Равномерное распределение по группам"""

    if request.user not in all_users:
        all_users.append(request.user)
        messages.success(request, 'Вы успешно вступили в группу')
    else:
        messages.add_message(request, 20, 'Вы уже состоите в группе')

    for group in groups:   # очищаем имеющиеся данные
        group.users.clear()

    used_groups = len(all_users) // product.min_users
    if used_groups >= len(groups):
        all_groups = groups
    elif used_groups == 0:
        all_groups = groups[0:]
    else:
        all_groups = groups[0:used_groups]

    while len(all_users) != 0:
        for group in all_groups:
            for user in all_users:
                group.users.add(user)
                all_users.remove(user)
                break


def to_maximum(request, all_users, groups, product):

    """Заполнение до макс значения"""

    if request.user not in all_users:
        for group in groups:
            if group.users.all().count() < product.max_users:
                group.users.add(request.user)
                break
        messages.success(request, 'Вы успешно вступили в группу')
    else:
        messages.add_message(request, 20, 'Вы уже состоите в группе')


def user_in_group(request, pk, function=same_distribution):
    product = Product.objects.get(pk=pk)
    groups = product.groups.all()
    all_users = []
    for group in groups:
        all_users.extend(group.users.all())

    function(request, all_users, groups, product)
    return redirect('products:detail_page', pk=pk)

task/users/views.py
from django.shortcuts import render

# Create your views here.

task/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView
from task.forms import LoginForm, RegisterForm


class IndexView(TemplateView):
    template_name = 'index.html'


class UserCreateView(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_message = "Пользователь успешно зарегистрирован"
    success_url = reverse_lazy('login_page')

    def form_valid(self, form):
        form.save()
        return super(UserCreateView, self).form_valid(form)


class LoginUser(SuccessMessageMixin, LoginView):
    form_class = LoginForm
    template_name = 'login.html'
    success_message = "Вы залогинены"

    def get_success_url(self):
        return reverse_lazy('products:index_page')


class LogoutUser(LogoutView):

    def get_success_url(self):
        messages.add_message(self.request, 20, 'Вы разлогинены')
        return reverse_lazy('products:index_page')

task/templates/base.html
<!doctype html>
<html>
{% load i18n %}
  <head>
    <title>{% block title %}{% endblock %}</title>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="navbar-brand" aria-current="page" href="{% url 'products:index_page' %}">{% translate 'Продукты' %}</a>
        </li>


        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
              <button class="btn btn-link" style="background: none">{% translate 'Выход' %}</button>
          </form>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login_page' %}">{% translate 'Вход' %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register_page' %}">{% translate 'Регистрация' %}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

    {% block content %}{% endblock %}
  </body>
</html>

task/templates/detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% endblock %}

{% load i18n %}

{% block content %}

{% if messages %}
    {% for message in messages %}
    <div class="text-center alert alert-{{ message.tags }}">
             {{ message }}
    </div>
    {% endfor %}
{% endif %}
<br><br>


<div class="container wrapper flex-grow-1">

<div class="card">
  <h5 class="card-header">{{ product.name }}</h5>
  <div class="card-body">
    <h5 class="card-title">{{ product.author }}</h5>
    <p class="card-text">{{ product.start_date }}</p>

      {% for lesson in lessons_of_product %}
    <div class="card w-75">
      <div class="card-body">
        <h5 class="card-title">{{ lesson.name }}</h5>
        <a href="{{ lesson.video }}" class="btn btn-primary">Перейти к уроку</a>
      </div>
    </div><br>
        {% endfor %}
      {% if time_perm %}
          {% if permission %}
          <a href="{% url 'products:buy_page' pk=product.id %}" class="btn btn-primary">Приобрести курс</a>
          {% else %}
          <p class="card-title">Группы переполнены</p>
          {% endif %}
      {% else %}
            <p class="card-title">Продукт начался</p>
      {% endif %}

  </div>
</div>


</div>

{% endblock %}

task/templates/index.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load i18n %}
{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'warning' %}
            <div class="text-center alert alert-danger">
                     {{ message }}
            </div>
        {% else %}
            <div class="text-center alert alert-{{ message.tags }}">
                     {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
<br><br>


<div class="container wrapper flex-grow-1">

    {% for product in products %}
        <div class="card">
          <h5 class="card-header">{{ product.name }}</h5>
          <div class="card-body">
            <h5 class="card-title">{{ product.author }}</h5>
            <p class="card-text">{{ product.start_date }}</p>
            <a href="{% url 'products:detail_page' pk=product.id %}" class="btn btn-primary">Перейти к продукту</a>
          </div>
        </div>
    {% endfor %}

</div>

{% endblock %}

task/templates/login.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'warning' %}
            <div class="text-center alert alert-danger">
                     {{ message }}
            </div>
        {% else %}
            <div class="text-center alert alert-{{ message.tags }}">
                     {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}
<br><br>
<div class="container wrapper flex-grow-1">

{% if form.errors %}
    <p class="text-danger">{% translate 'Пожалуйста, введите правильные имя пользователя и пароль. Оба поля могут быть чувствительны к регистру.' %}</p>
{% endif %}

<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="fieldWrapper mb-3">
      {% bootstrap_field field placeholder='' show_help=False %}
    </div>
  {% endfor %}
  <input class="btn btn-outline-warning me-2" type="submit" value="{% translate 'Войти' %}">
</form>

</div>
{% endblock %}

task/templates/register.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% load i18n %}

{% block content %}
<br><br>
<div class="container wrapper flex-grow-1">

<form method="post">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <input class="btn btn-outline-warning me-2" type="submit" value="{% translate 'Зарегистрироваться' %}">

</form>

</div>
{% endblock %}